AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Manager Customers

iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      - lambda:InvokeFunction # Added this like mentioned above
    Resource:
      - arn:aws:dynamodb:ap-southeast-1:*:*
      - arn:aws:lambda:ap-southeast-1:*:* # Had to add this too

Resources:
  UserApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'*'"

  MyTemplate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.index
      Runtime: python3.8
      Timeout: 180
      CodeUri: myFunctions/

      Events:
        postLogin:
          Type: Api
          Properties:
            Path: /login
            Method: post
            RestApiId:
              Ref: UserApi
        # DeleteIndex:
        #   Type: Api
        #   Properties:
        #     Path: /deleteIndex
        #     Method: delete
        #     RestApiId:
        #       Ref: UserApi
        # GetItem:
        #   Type: Api
        #   Properties:
        #     Path: /getItemIndex
        #     Method: get
        #     RestApiId:
        #       Ref: UserApi
        # PostItem:
        #   Type: Api
        #   Properties:
        #     Path: /postItemIndex
        #     Method: post
        #     RestApiId:
        #       Ref: UserApi
