AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Manager Customers

Resources:
  UserApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
        AllowMethods: "'*'"

  MyTemplate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.index
      Runtime: python3.8
      Timeout: 180
      CodeUri: myFunctions/
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess

      Events:
        postAllItems:
          Type: Api
          Properties:
            Path: /postAllItems
            Method: post
            RestApiId:
              Ref: UserApi

        postItem:
          Type: Api
          Properties:
            Path: /postItem
            Method: post
            RestApiId:
              Ref: UserApi

        postLogin:
          Type: Api
          Properties:
            Path: /login
            Method: post
            RestApiId:
              Ref: UserApi

        getListItems:
          Type: Api
          Properties:
            Path: /getAllItems
            Method: get
            RestApiId:
              Ref: UserApi

        getItem:
          Type: Api
          Properties:
            Path: /getItem
            Method: get
            RestApiId:
              Ref: UserApi

        updateItem:
          Type: Api
          Properties:
            Path: /updateItem
            Method: put
            RestApiId:
              Ref: UserApi

        forgotPassword:
          Type: Api
          Properties:
            Path: /forgot-password
            Method: post
            RestApiId:
              Ref: UserApi
