AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Manager Customers

Resources:
  UserApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'*'"
        AllowOrigin: "'http://localhost:4200'"

  MyTemplate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.index
      Runtime: python3.8
      Timeout: 180
      CodeUri: myFunctions/
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess

      Events:
        postAllItems:
          Type: Api
          Properties:
            Path: /postAllItems
            Method: post
            RestApiId:
              Ref: UserApi

        postLogin:
          Type: Api
          Properties:
            Path: /login
            Method: post
            RestApiId:
              Ref: UserApi

        getListItems:
          Type: Api
          Properties:
            Path: /getAllItems
            Method: get
            RestApiId:
              Ref: UserApi
        # GetItem:
        #   Type: Api
        #   Properties:
        #     Path: /getItemIndex
        #     Method: get
        #     RestApiId:
        #       Ref: UserApi
        # PostItem:
        #   Type: Api
        #   Properties:
        #     Path: /postItemIndex
        #     Method: post
        #     RestApiId:
        #       Ref: UserApi
