AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Manager Customers

Resources:
  UserApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'*'"

  MyTemplate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.index
      Runtime: python3.8
      Timeout: 180
      CodeUri: myFunction/

      # Policies:
      #   - DynamoDBCrudPolicy:
      #       TableName: !Ref MyTable

      Events:
        CreateIndex:
          Type: Api
          Properties:
            Path: /createIndex
            Method: put
            RestApiId:
              Ref: UserApi
        DeleteIndex:
          Type: Api
          Properties:
            Path: /deleteIndex
            Method: delete
            RestApiId:
              Ref: UserApi
        GetItem:
          Type: Api
          Properties:
            Path: /getItemIndex
            Method: get
            RestApiId:
              Ref: UserApi
        PostItem:
          Type: Api
          Properties:
            Path: /postItemIndex
            Method: post
            RestApiId:
              Ref: UserApi
